// app/layout.tsx

import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/auth/auth-provider";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { getServerAuthSession } from "@/dal/features/auth/server";
import { robotoMono, robotoSans } from "./fonts";


export const metadata: Metadata = {
  title: "CFB 27 - Dynasty Tracker",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode}>) {
  const serverSession = await getServerAuthSession();
  return (
    <html
      lang="en"
      className={`${robotoSans.variable} ${robotoMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans bg-background">
        <ThemeProvider>
          <AuthProvider serverSession={serverSession}>
            <main className="flex-1 bg-background text-foreground">
              {children}
            </main>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
