// lib/fbs-teams.ts

export interface SchoolColors {
    primary: string;
    secondary: string;
    accent?: string;
    extra?: string;
}

export interface FbsTeam {
    id: string;
    name: string;
    nickName: string;
    city: string;
    state: string;
    conference: string;
    stadium: string;
    abbrev: string;
    colors: SchoolColors;
    logo: string;
}

export const fbsTeams: FbsTeam[] = [
    {
        id: "afa",
        name: "Air Force",
        nickName: "Falcons",
        city: "Colorado Springs",
        state: "Colorado",
        conference: "MWC",
        stadium: "Falcon Stadium",
        abbrev: "AFA",
        colors: {
            primary: "#00308f",
            secondary: "#a6a6a8",
        },
        logo: "/logos/Air_Force_Falcons_logo_300x300.png",
    },
    {
        id: "akr",
        name: "Akron",
        nickName: "Zips",
        city: "Akron",
        state: "Ohio",
        conference: "MAC",
        stadium: "InfoCision Stadium",
        abbrev: "AKR",
        colors: {
            primary: "#002147",
            secondary: "#918b4c",
        },
        logo: "/logos/Akron_Zips_logo_300x300.png",
    },
    {
        id: "bama",
        name: "Alabama",
        nickName: "Crimson Tide",
        city: "Tuscaloosa",
        state: "Alabama",
        conference: "SEC",
        stadium: "Bryant-Denny Stadium",
        abbrev: "BAMA",
        colors: {
            primary: "#9e1b32",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Alabama_Crimson_Tide_logo_300x300.png",
    },
    {
        id: "app",
        name: "Appalachian State",
        nickName: "Mountaineers",
        city: "Boone",
        state: "North Carolina",
        conference: "Sun Belt",
        stadium: "Kidd Brewer Stadium",
        abbrev: "APP",
        colors: {
            primary: "#222222",
            secondary: "#ffcc00",
        },
        logo: "/logos/Appalachian_State_Mountaineers_logo_300x300.png",
    },
    {
        id: "ariz",
        name: "Arizona",
        nickName: "Wildcats",
        city: "Tucson",
        state: "Arizona",
        conference: "Big 12",
        stadium: "Arizona Stadium",
        abbrev: "ARIZ",
        colors: {
            primary: "#AB0520",
            secondary: "#0C234B",
        },
        logo: "/logos/Arizona_Wildcats_logo_300x300.png",
    },
    {
        id: "asu",
        name: "Arizona State",
        nickName: "Sun Devils",
        city: "Tempe",
        state: "Arizona",
        conference: "Big 12",
        stadium: "Sun Devil Stadium",
        abbrev: "ASU",
        colors: {
            primary: "#990033",
            secondary: "#FFB310",
        },
        logo: "/logos/Arizona_State_Sun_Devils_logo_300x300.png",
    },
    {
        id: "ark",
        name: "Arkansas",
        nickName: "Razorbacks",
        city: "Fayetteville",
        state: "Arkansas",
        conference: "SEC",
        stadium: "Donald W. Reynolds Razorback Stadium",
        abbrev: "ARK",
        colors: {
            primary: "#9D2235",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Arkansas_Razorbacks_logo_300x300.png",
    },
    {
        id: "arst",
        name: "Arkansas State",
        nickName: "Red Wolves",
        city: "Jonesboro",
        state: "Arkansas",
        conference: "Sun Belt",
        stadium: "Centennial Bank Stadium",
        abbrev: "ARST",
        colors: {
            primary: "#cc092f",
            secondary: "#000000",
            accent: "#FFFFFF",
        },
        logo: "/logos/Arkansas_State_Red_Wolves_logo_300x300.png",
    },
    {
        id: "army",
        name: "Army",
        nickName: "Black Knights",
        city: "West Point",
        state: "New York",
        conference: "AAC",
        stadium: "Michie Stadium",
        abbrev: "ARMY",
        colors: {
            primary: "#000000",
            secondary: "#d3bc8d",
        },
        logo: "/logos/Army_Black_Knights_logo_300x300.png",
    },
    {
        id: "aub",
        name: "Auburn",
        nickName: "Tigers",
        city: "Auburn",
        state: "Alabama",
        conference: "SEC",
        stadium: "Jordan-Hare Stadium",
        abbrev: "AUB",
        colors: {
            primary: "#0C2340",
            secondary: "#F26522",
        },
        logo: "/logos/Auburn_Tigers_logo_300x300.png",
    },
    {
        id: "ball",
        name: "Ball State",
        nickName: "Cardinals",
        city: "Muncie",
        state: "Indiana",
        conference: "MAC",
        stadium: "Scheumann Stadium",
        abbrev: "BALL",
        colors: {
            primary: "#BA0C2F",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Ball_State_Cardinals_logo_300x300.png",
    },
    {
        id: "bay",
        name: "Baylor",
        nickName: "Bears",
        city: "Waco",
        state: "Texas",
        conference: "Big 12",
        stadium: "McLane Stadium",
        abbrev: "BAY",
        colors: {
            primary: "#003015",
            secondary: "#fecb00",
        },
        logo: "/logos/Baylor_Bears_logo_300x300.png",
    },
    {
        id: "bsu",
        name: "Boise State",
        nickName: "Broncos",
        city: "Boise",
        state: "Idaho",
        conference: "Pac-12",
        stadium: "Albertsons Stadium",
        abbrev: "BSU",
        colors: {
            primary: "#09347A",
            secondary: "#F1632A",
        },
        logo: "/logos/Boise_State_Broncos_Logo_300x300.png",
    },
    {
        id: "bc",
        name: "Boston College",
        nickName: "Eagles",
        city: "Chestnut Hill",
        state: "Massachusetts",
        conference: "ACC",
        stadium: "Alumni Stadium",
        abbrev: "BC",
        colors: {
            primary: "#910039",
            secondary: "#B38F59",
        },
        logo: "/logos/Boston_College_Eagles_logo_300x300.png",
    },
    {
        id: "bgsu",
        name: "Bowling Green",
        nickName: "Falcons",
        city: "Bowling Green",
        state: "Ohio",
        conference: "MAC",
        stadium: "Doyt Perry Stadium",
        abbrev: "BGSU",
        colors: {
            primary: "#4F2C1D",
            secondary: "#FE5000",
        },
        logo: "/logos/Bowling_Green_Falcons_logo_300x300.png",
    },
    {
        id: "buff",
        name: "Buffalo",
        nickName: "Bulls",
        city: "Amherst",
        state: "New York",
        conference: "MAC",
        stadium: "UB Stadium",
        abbrev: "BUFF",
        colors: {
            primary: "#005bbb",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Buffalo_Bulls_logo_300x300.png",
    },
    {
        id: "byu",
        name: "BYU",
        nickName: "Cougars",
        city: "Provo",
        state: "Utah",
        conference: "Big 12",
        stadium: "LaVell Edwards Stadium",
        abbrev: "BYU",
        colors: {
            primary: "#002255",
            secondary: "#FFFFFF",
        },
        logo: "/logos/BYU_Cougars_logo_300x300.png",
    },
    {
        id: "cal",
        name: "California",
        nickName: "Golden Bears",
        city: "Berkeley",
        state: "California",
        conference: "ACC",
        stadium: "California Memorial Stadium",
        abbrev: "CAL",
        colors: {
            primary: "#041E42",
            secondary: "#FFC72C",
        },
        logo: "/logos/California_Golden_Bears_logo_300x300.png",
    },
    {
        id: "cmu",
        name: "Central Michigan",
        nickName: "Chippewas",
        city: "Mount Pleasant",
        state: "Michigan",
        conference: "MAC",
        stadium: "Kelly/Shorts Stadium",
        abbrev: "CMU",
        colors: {
            primary: "#6a0032",
            secondary: "#ffc82e",
        },
        logo: "/logos/Central_Michigan_Chippewas_logo_300x300.png",
    },
    {
        id: "char",
        name: "Charlotte",
        nickName: "49ers",
        city: "Charlotte",
        state: "North Carolina",
        conference: "AAC",
        stadium: "Jerry Richardson Stadium",
        abbrev: "CHAR",
        colors: {
            primary: "#046a38",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Charlotte_49ers_logo_300x300.png",
    },
    {
        id: "cin",
        name: "Cincinnati",
        nickName: "Bearcats",
        city: "Cincinnati",
        state: "Ohio",
        conference: "Big 12",
        stadium: "Nippert Stadium",
        abbrev: "CIN",
        colors: {
            primary: "#000000",
            secondary: "#E00122",
        },
        logo: "/logos/Cincinnati_Bearcats_logo_300x300.png",
    },
    {
        id: "clem",
        name: "Clemson",
        nickName: "Tigers",
        city: "Clemson",
        state: "South Carolina",
        conference: "ACC",
        stadium: "Memorial Stadium",
        abbrev: "CLEM",
        colors: {
            primary: "#F56600",
            secondary: "#522D80",
        },
        logo: "/logos/Clemson_Tigers_logo_300x300.png",
    },
    {
        id: "ccar",
        name: "Coastal Carolina",
        nickName: "Chanticleers",
        city: "Conway",
        state: "South Carolina",
        conference: "Sun Belt",
        stadium: "Brooks Stadium",
        abbrev: "CCAR",
        colors: {
            primary: "#007c89",
            secondary: "#231f20",
        },
        logo: "/logos/Coastal_Carolina_Chanticleers_logo_300x300.png",
    },
    {
        id: "colo",
        name: "Colorado",
        nickName: "Buffaloes",
        city: "Boulder",
        state: "Colorado",
        conference: "Big 12",
        stadium: "Folsom Field",
        abbrev: "COLO",
        colors: {
            primary: "#000000",
            secondary: "#CFB87C",
            accent: "#A2A4A3",
        },
        logo: "/logos/Colorado_Buffaloes_logo_300x300.png",
    },
    {
        id: "csu",
        name: "Colorado State",
        nickName: "Rams",
        city: "Fort Collins",
        state: "Colorado",
        conference: "Pac-12",
        stadium: "Canvas Stadium",
        abbrev: "CSU",
        colors: {
            primary: "#1E4D2B",
            secondary: "#C8C372",
        },
        logo: "/logos/Colorado_State_Rams_logo_300x300.png",
    },
    {
        id: "du",
        name: "Delaware",
        nickName: "Blue Hens",
        city: "Newark",
        state: "Delaware",
        conference: "C-USA",
        stadium: "Delaware Stadium",
        abbrev: "DU",
        colors: {
            primary: "#00539f",
            secondary: "#FFDD31",
            accent: "#ffd200",
        },
        logo: "/logos/Delaware_Blue_Hens_logo_300x300.png",
    },
    {
        id: "duke",
        name: "Duke",
        nickName: "Blue Devils",
        city: "Durham",
        state: "North Carolina",
        conference: "ACC",
        stadium: "Wallace Wade Stadium",
        abbrev: "DUKE",
        colors: {
            primary: "#001A57",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Duke_Blue_Devils_logo_300x300.png",
    },
    {
        id: "ecu",
        name: "East Carolina",
        nickName: "Pirates",
        city: "Greenville",
        state: "North Carolina",
        conference: "AAC",
        stadium: "Dowdy-Ficklen Stadium",
        abbrev: "ECU",
        colors: {
            primary: "#592A8A",
            secondary: "#FDC82F",
        },
        logo: "/logos/East_Carolina_Pirates_logo_300x300.png",
    },
    {
        id: "emu",
        name: "Eastern Michigan",
        nickName: "Eagles",
        city: "Ypsilanti",
        state: "Michigan",
        conference: "MAC",
        stadium: "Rynearson Stadium",
        abbrev: "EMU",
        colors: {
            primary: "#006633",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Eastern_Michigan_Eagles_logo_300x300.png",
    },
    {
        id: "fiu",
        name: "FIU",
        nickName: "Panthers",
        city: "Westchester",
        state: "Florida",
        conference: "C-USA",
        stadium: "Pitbull Stadium",
        abbrev: "FIU",
        colors: {
            primary: "#081E3F",
            secondary: "#B6862C",
        },
        logo: "/logos/FIU_Panthers_Logo_300x300.png",
    },
    {
        id: "fla",
        name: "Florida",
        nickName: "Gators",
        city: "Gainesville",
        state: "Florida",
        conference: "SEC",
        stadium: "Ben Hill Griffin Stadium",
        abbrev: "FLA",
        colors: {
            primary: "#0021a5",
            secondary: "#FA4616",
        },
        logo: "/logos/Florida_Gators_logo_300x300.png",
    },
    {
        id: "fau",
        name: "Florida Atlantic",
        nickName: "Owls",
        city: "Boca Raton",
        state: "Florida",
        conference: "AAC",
        stadium: "FAU Stadium",
        abbrev: "FAU",
        colors: {
            primary: "#003366",
            secondary: "#CC0000",
        },
        logo: "/logos/Florida_Atlantic_Owls_logo_300x300.png",
    },
    {
        id: "fsu",
        name: "Florida State",
        nickName: "Seminoles",
        city: "Tallahassee",
        state: "Florida",
        conference: "ACC",
        stadium: "Bobby Bowden Field at Doak Campbell Stadium",
        abbrev: "FSU",
        colors: {
            primary: "#782F40",
            secondary: "#CEB888",
        },
        logo: "/logos/Florida_State_Seminoles_logo_300x300.png",
    },
    {
        id: "fres",
        name: "Fresno State",
        nickName: "Bulldogs",
        city: "Fresno",
        state: "California",
        conference: "Pac-12",
        stadium: "Valley Children's Stadium",
        abbrev: "FRES",
        colors: {
            primary: "#C41230",
            secondary: "#002C76",
        },
        logo: "/logos/Fresno_State_Bulldogs_logo_300x300.png",
    },
    {
        id: "uga",
        name: "Georgia",
        nickName: "Bulldogs",
        city: "Athens",
        state: "Georgia",
        conference: "SEC",
        stadium: "Sanford Stadium",
        abbrev: "UGA",
        colors: {
            primary: "#DA291C",
            secondary: "#000000",
        },
        logo: "/logos/Georgia_Bulldogs_logo_300x300.png",
    },
    {
        id: "gaso",
        name: "Georgia Southern",
        nickName: "Eagles",
        city: "Statesboro",
        state: "Georgia",
        conference: "Sun Belt",
        stadium: "Paulson Stadium",
        abbrev: "GASO",
        colors: {
            primary: "#011e41",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Georgia_Southern_Eagles_logo_300x300.png",
    },
    {
        id: "gsu",
        name: "Georgia State",
        nickName: "Panthers",
        city: "Atlanta",
        state: "Georgia",
        conference: "Sun Belt",
        stadium: "Georgia State Stadium",
        abbrev: "GSU",
        colors: {
            primary: "#0039A6",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Georgia_State_Panthers_logo_300x300.png",
    },
    {
        id: "gt",
        name: "Georgia Tech",
        nickName: "Yellow Jackets",
        city: "Atlanta",
        state: "Georgia",
        conference: "ACC",
        stadium: "Bobby Dodd Stadium at Historic Grant Field",
        abbrev: "GT",
        colors: {
            primary: "#C59353",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Georgia_Tech_Yellow_Jackets_logo_300x300.png",
    },
    {
        id: "haw",
        name: "Hawaii",
        nickName: "Rainbow Warriors",
        city: "Honolulu",
        state: "Hawaii",
        conference: "MWC",
        stadium: "Clarence T. C. Ching Athletics Complex",
        abbrev: "HAW",
        colors: {
            primary: "#024731",
            secondary: "#FFFFFF",
            accent: "#000000",
            extra: "#C0C0C0",
        },
        logo: "/logos/Hawaii_Rainbow_Warriors_logo_300x300.png",
    },
    {
        id: "hou",
        name: "Houston",
        nickName: "Cougars",
        city: "Houston",
        state: "Texas",
        conference: "Big 12",
        stadium: "TDECU Stadium",
        abbrev: "HOU",
        colors: {
            primary: "#C92839",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Houston_Cougars_logo_300x300.png",
    },
    {
        id: "ill",
        name: "Illinois",
        nickName: "Fighting Illini",
        city: "Champaign",
        state: "Illinois",
        conference: "Big Ten",
        stadium: "Memorial Stadium",
        abbrev: "ILL",
        colors: {
            primary: "#e04e39",
            secondary: "#13294b",
        },
        logo: "/logos/Illinois_Fighting_Illini_logo_300x300.png",
    },
    {
        id: "ind",
        name: "Indiana",
        nickName: "Hoosiers",
        city: "Bloomington",
        state: "Indiana",
        conference: "Big Ten",
        stadium: "Memorial Stadium",
        abbrev: "IND",
        colors: {
            primary: "#990000",
            secondary: "#EEEDEB",
        },
        logo: "/logos/Indiana_Hoosiers_logo_300x300.png",
    },
    {
        id: "iowa",
        name: "Iowa",
        nickName: "Hawkeyes",
        city: "Iowa City",
        state: "Iowa",
        conference: "Big Ten",
        stadium: "Nile Kinnick Stadium",
        abbrev: "IOWA",
        colors: {
            primary: "#000000",
            secondary: "#FFE100",
        },
        logo: "/logos/Iowa_Hawkeyes_logo_300x300.png",
    },
    {
        id: "isu",
        name: "Iowa State",
        nickName: "Cyclones",
        city: "Ames",
        state: "Iowa",
        conference: "Big 12",
        stadium: "Jack Trice Stadium",
        abbrev: "ISU",
        colors: {
            primary: "#a6192e",
            secondary: "#FDC82F",
        },
        logo: "/logos/Iowa_State_Cyclones_logo_300x300.png",
    },
    {
        id: "jvst",
        name: "Jacksonville State",
        nickName: "Gamecocks",
        city: "Jacksonville",
        state: "Alabama",
        conference: "C-USA",
        stadium: "Burgess-Snow Field at JSU Stadium",
        abbrev: "JVST",
        colors: {
            primary: "#a6192e",
            secondary: "#000000",
        },
        logo: "/logos/Jacksonville_State_Gamecocks_logo_300x300.png",
    },
    {
        id: "jmu",
        name: "James Madison",
        nickName: "Dukes",
        city: "Harrisonburg",
        state: "Virginia",
        conference: "Sun Belt",
        stadium: "Bridgeforth Stadium",
        abbrev: "JMU",
        colors: {
            primary: "#450084",
            secondary: "#f4c800",
        },
        logo: "/logos/James_Madison_Dukes_logo_300x300.png",
    },
    {
        id: "ku",
        name: "Kansas",
        nickName: "Jayhawks",
        city: "Lawrence",
        state: "Kansas",
        conference: "Big 12",
        stadium: "David Booth Kansas Memorial Stadium",
        abbrev: "KU",
        colors: {
            primary: "#0051BA",
            secondary: "#E8000D",
        },
        logo: "/logos/Kansas_Jayhawks_logo_300x300.png",
    },
    {
        id: "ksu",
        name: "Kansas State",
        nickName: "Wildcats",
        city: "Manhattan",
        state: "Kansas",
        conference: "Big 12",
        stadium: "Bill Snyder Family Football Stadium",
        abbrev: "KSU",
        colors: {
            primary: "#512888",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Kansas_State_Wildcats_logo_300x300.png",
    },
    {
        id: "kenn",
        name: "Kennesaw State",
        nickName: "Owls",
        city: "Kennesaw",
        state: "GA",
        conference: "C-USA",
        stadium: "Fifth Third Stadium",
        abbrev: "KENN",
        colors: {
            primary: "#000000",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Kennesaw_State_Owls_logo_300x300.png",
    },
    {
        id: "kent",
        name: "Kent State",
        nickName: "Golden Flashes",
        city: "Kent",
        state: "Ohio",
        conference: "MAC",
        stadium: "Dix Stadium",
        abbrev: "KENT",
        colors: {
            primary: "#002664",
            secondary: "#EAAB00",
        },
        logo: "/logos/Kent_State_Golden_Flashes_300x300.png",
    },
    {
        id: "uk",
        name: "Kentucky",
        nickName: "Wildcats",
        city: "Lexington",
        state: "Kentucky",
        conference: "SEC",
        stadium: "Kroger Field",
        abbrev: "UK",
        colors: {
            primary: "#0033A0",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Kentucky_Wildcats_logo_300x300.png",
    },
    {
        id: "lib",
        name: "Liberty",
        nickName: "Flames",
        city: "Lynchburg",
        state: "Virginia",
        conference: "C-USA",
        stadium: "Williams Stadium",
        abbrev: "LIB",
        colors: {
            primary: "#041e42",
            secondary: "#be1e2d",
        },
        logo: "/logos/Liberty_Flames_logo_300x300.png",
    },
    {
        id: "ull",
        name: "Louisiana",
        nickName: "Ragin Cajuns",
        city: "Lafayette",
        state: "Louisiana",
        conference: "Sun Belt",
        stadium: "Cajun Field",
        abbrev: "ULL",
        colors: {
            primary: "#ce181e",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Louisiana_Ragin_Cajuns_logo_300x300.png",
    },
    {
        id: "lt",
        name: "Louisiana Tech",
        nickName: "Bulldogs",
        city: "Ruston",
        state: "Louisiana",
        conference: "Sun Belt",
        stadium: "Joe Aillet Stadium",
        abbrev: "LT",
        colors: {
            primary: "#003087",
            secondary: "#CB333B",
        },
        logo: "/logos/Louisiana_Tech_Bulldogs_logo_300x300.png",
    },
    {
        id: "ulm",
        name: "Louisiana-Monroe",
        nickName: "Warhawks",
        city: "Monroe",
        state: "Louisiana",
        conference: "Sun Belt",
        stadium: "JPS Field at Malone Stadium",
        abbrev: "ULM",
        colors: {
            primary: "#800029",
            secondary: "#bd955a",
        },
        logo: "/logos/Louisiana-Monroe_Warhawks_300x300.png",
    },
    {
        id: "lou",
        name: "Louisville",
        nickName: "Cardinals",
        city: "Louisville",
        state: "Kentucky",
        conference: "ACC",
        stadium: "L&N Federal Credit Union Stadium",
        abbrev: "LOU",
        colors: {
            primary: "#AD0000",
            secondary: "#000000",
        },
        logo: "/logos/Louisville_Cardinals_logo_300x300.png",
    },
    {
        id: "lsu",
        name: "LSU",
        nickName: "Tigers",
        city: "Baton Rouge",
        state: "Louisiana",
        conference: "SEC",
        stadium: "Tiger Stadium",
        abbrev: "LSU",
        colors: {
            primary: "#582c83",
            secondary: "#ffc72c",
        },
        logo: "/logos/LSU_Tigers_300x300.png",
    },
    {
        id: "mrsh",
        name: "Marshall",
        nickName: "Thundering Herd",
        city: "Huntington",
        state: "West Virginia",
        conference: "Sun Belt",
        stadium: "Joan C. Edwards Stadium",
        abbrev: "MRSH",
        colors: {
            primary: "#006140",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Marshall_Thundering_Herd_logo_300x300.png",
    },
    {
        id: "umd",
        name: "Maryland",
        nickName: "Terrapins",
        city: "College Park",
        state: "Maryland",
        conference: "Big Ten",
        stadium: "SECU Stadium",
        abbrev: "UMD",
        colors: {
        primary: "#c8102e",
            secondary: "#FFFFFF",
            accent: "#000000",
            extra: "#FFCD00",
        },
        logo: "/logos/Maryland_Terrapins_logo_300x300.png",
    },
    {
        id: "mem",
        name: "Memphis",
        nickName: "Tigers",
        city: "Memphis",
        state: "Tennessee",
        conference: "AAC",
        stadium: "Simmons Bank Liberty Stadium",
        abbrev: "MEM",
        colors: {
            primary: "#0D3182",
            secondary: "#888C8F",
        },
        logo: "/logos/Memphis_Tigers_logo_300x300.png",
    },
    {
        id: "mia",
        name: "Miami (FL)",
        nickName: "Hurricanes",
        city: "Mami Gardens",
        state: "Florida",
        conference: "ACC",
        stadium: "Hard Rock Stadium",
        abbrev: "MIA",
        colors: {
            primary: "#005030",
            secondary: "#f47321",
        },
        logo: "/logos/Miami_FL_Hurricanes_logo_300x300.png",
    },
    {
        id: "m-oh",
        name: "Miami (OH)",
        nickName: "RedHawks",
        city: "Oxford",
        state: "Ohio",
        conference: "MAC",
        stadium: "Yager Stadium",
        abbrev: "M-OH",
        colors: {
            primary: "#B61E2E",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Miami_OH_Redhawks_logo_300x300.png",
    },
    {
        id: "mich",
        name: "Michigan",
        nickName: "Wolverines",
        city: "Ann Arbor",
        state: "Michigan",
        conference: "Big Ten",
        stadium: "Michigan Stadium",
        abbrev: "MICH",
        colors: {
            primary: "#ffcb05",
            secondary: "#00274c",
        },
        logo: "/logos/Michigan_Wolverines_logo_300x300.png",
    },
    {
        id: "msu",
        name: "Michigan State",
        nickName: "Spartans",
        city: "East Lansing",
        state: "Michigan",
        conference: "Big Ten",
        stadium: "Spartan Stadium",
        abbrev: "MSU",
        colors: {
            primary: "#18453B",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Michigan_State_Spartans_logo_300x300.png",
    },
    {
        id: "mtsu",
        name: "Middle Tennessee",
        nickName: "Blue Raiders",
        city: "Murfreesboro",
        state: "Tennessee",
        conference: "C-USA",
        stadium: "Johnny Red Floyd Stadium",
        abbrev: "MTSU",
        colors: {
            primary: "#0066CC",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Middle_Tennessee_Blue_Raiders_logo_300x300.png",
    },
    {
        id: "minn",
        name: "Minnesota",
        nickName: "Golden Gophers",
        city: "Minneapolis",
        state: "Minnesota",
        conference: "Big Ten",
        stadium: "Huntington Bank Stadium",
        abbrev: "MINN",
        colors: {
            primary: "#7a0019",
            secondary: "#ffcc33",
        },
        logo: "/logos/Minnesota_Golden_Gophers_logo_300x300.png",
    },
    {
        id: "msst",
        name: "Mississippi State",
        nickName: "Bulldogs",
        city: "Starkville",
        state: "Mississippi",
        conference: "SEC",
        stadium: "Davis Wade Stadium",
        abbrev: "MSST",
        colors: {
            primary: "#660000",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Mississippi_State_Bulldogs_logo_300x300.png",
    },
    {
        id: "mizz",
        name: "Missouri",
        nickName: "Tigers",
        city: "Columbia",
        state: "Missouri",
        conference: "SEC",
        stadium: "Faurot Field at Memorial Stadium",
        abbrev: "MIZZ",
        colors: {
            primary: "#000000",
            secondary: "#F1B82D",
        },
        logo: "/logos/Missouri_Tigers_logo_300x300.png",
    },
    {
        id: "mist",
        name: "Missouri State",
        nickName: "Bears",
        city: "Springfield",
        state: "Missouri",
        conference: "C-USA",
        stadium: "\tRobert W. Plaster Stadium",
        abbrev: "MIST",
        colors: {
            primary: "#5E0009",
            secondary: "#FFFFFF",
            accent: "#000000",
        },
        logo: "/logos/Missouri_State_Bears_logo_300x300.png",
    },
    {
        id: "navy",
        name: "Navy",
        nickName: "Midshipmen",
        city: "Annapolis",
        state: "Maryland",
        conference: "AAC",
        stadium: "Navy-Marine Corps Memorial Stadium",
        abbrev: "NAVY",
        colors: {
            primary: "#00205b",
            secondary: "#c5b783",
        },
        logo: "/logos/Navy_Midshipmen_logo_300x300.png",
    },
    {
        id: "ncst",
        name: "NC State",
        nickName: "Wolfpack",
        city: "Raleigh",
        state: "North Carolina",
        conference: "ACC",
        stadium: "Carter-Finley Stadium",
        abbrev: "NCST",
        colors: {
            primary: "#CC0000",
            secondary: "#000000",
            accent: "#FFFFFF",
        },
        logo: "/logos/NC_State_Wolfpack_logo_300x300.png",
    },
    {
        id: "neb",
        name: "Nebraska",
        nickName: "Cornhuskers",
        city: "Lincoln",
        state: "Nebraska",
        conference: "Big Ten",
        stadium: "Memorial Stadium",
        abbrev: "NEB",
        colors: {
            primary: "#e41c38",
            secondary: "#fdf2d9",
        },
        logo: "/logos/Nebraska_Cornhuskers_logo_300x300.png",
    },
    {
        id: "nev",
        name: "Nevada",
        nickName: "Wolf Pack",
        city: "Reno",
        state: "Nevada",
        conference: "MWC",
        stadium: "Mackay Stadium",
        abbrev: "NEV",
        colors: {
            primary: "#003366",
            secondary: "#807f84",
        },
        logo: "/logos/Nevada_Wolf_Pack_logo_300x300.png",
    },
    {
        id: "unm",
        name: "New Mexico",
        nickName: "Lobos",
        city: "Albuquerque",
        state: "New Mexico",
        conference: "MWC",
        stadium: "University Stadium",
        abbrev: "UNM",
        colors: {
            primary: "#B71234",
            secondary: "#C3C8C8",
        },
        logo: "/logos/New_Mexico_Lobos_logo_300x300.png",
    },
    {
        id: "nmsu",
        name: "New Mexico State",
        nickName: "Aggies",
        city: "Las Cruces",
        state: "New Mexico",
        conference: "C-USA",
        stadium: "Aggie Memorial Stadium",
        abbrev: "NMSU",
        colors: {
            primary: "#8c0b42",
            secondary: "#FFFFFF",
        },
        logo: "/logos/New_Mexico_State_Aggies_logo_300x300.png",
    },
    {
        id: "unc",
        name: "North Carolina",
        nickName: "Tar Heels",
        city: "Chapel Hill",
        state: "North Carolina",
        conference: "ACC",
        stadium: "Kenan Memorial Stadium",
        abbrev: "UNC",
        colors: {
            primary: "#7BAFD4",
            secondary: "#FFFFFF",
        },
        logo: "/logos/North_Carolina_Tar_Heels_logo_300x300.png",
    },
    {
        id: "ndsu",
        name: "North Dakota State",
        nickName: "Bison",
        city: "Fargo",
        state: "North Dakota",
        conference: "MWC",
        stadium: "Gate City Bank Field at the Fargodome",
        abbrev: "NDSU",
        colors: {
            primary: "#006633",
            secondary: "#FFC72C",
        },
        logo: "/logos/North_Dakota_State_Bison_logo_300x300.png",
    },
    {
        id: "unt",
        name: "North Texas",
        nickName: "Mean Green",
        city: "Denton",
        state: "Texas",
        conference: "AAC",
        stadium: "DATCU Stadium",
        abbrev: "UNT",
        colors: {
            primary: "#00853E",
            secondary: "#FFFFFF",
        },
        logo: "/logos/North_Texas_Mean_Green_logo_300x300.png",
    },
    {
        id: "niu",
        name: "Northern Illinois",
        nickName: "Huskies",
        city: "DeKalb",
        state: "Illinois",
        conference: "MWC",
        stadium: "Huskie Stadium",
        abbrev: "NIU",
        colors: {
            primary: "#ba0c2f",
            secondary: "#000000",
        },
        logo: "/logos/Northern_Illinois_Huskies_300x300.png",
    },
    {
        id: "nw",
        name: "Northwestern",
        nickName: "Wildcats",
        city: "Evanston",
        state: "Illinois",
        conference: "Big Ten",
        stadium: "Martin Stadium",
        abbrev: "NW",
        colors: {
            primary: "#4E2A84",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Northwestern_Wildcats_logo_300x300.png",
    },
    {
        id: "nd",
        name: "Notre Dame",
        nickName: "Fighting Irish",
        city: "Notre Dame",
        state: "Indiana",
        conference: "Independents",
        stadium: "Notre Dame Stadium",
        abbrev: "ND",
        colors: {
            primary: "#0C2340",
            secondary: "#C99700",
        },
        logo: "/logos/Notre_Dame_Fighting_Irish_logo_300x300.png",
    },
    {
        id: "ohio",
        name: "Ohio",
        nickName: "Bobcats",
        city: "Athens",
        state: "Ohio",
        conference: "MAC",
        stadium: "Peden Stadium",
        abbrev: "OHIO",
        colors: {
            primary: "#00694E",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Ohio_Bobcats_logo_300x300.png",
    },
    {
        id: "osu",
        name: "Ohio State",
        nickName: "Buckeyes",
        city: "Columbus",
        state: "Ohio",
        conference: "Big Ten",
        stadium: "Ohio Stadium",
        abbrev: "OSU",
        colors: {
            primary: "#bb0000",
            secondary: "#666666",
        },
        logo: "/logos/Ohio_State_Buckeyes_logo_300x300.png",
    },
    {
        id: "ou",
        name: "Oklahoma",
        nickName: "Sooners",
        city: "Norman",
        state: "Oklahoma",
        conference: "SEC",
        stadium: "Gaylord Family Oklahoma Memorial Stadium",
        abbrev: "OU",
        colors: {
            primary: "#841617",
            secondary: "#FDF9D8",
        },
        logo: "/logos/Oklahoma_Sooners_logo_300x300.png",
    },
    {
        id: "okst",
        name: "Oklahoma State",
        nickName: "Cowboys",
        city: "Stillwater",
        state: "Oklahoma",
        conference: "Big 12",
        stadium: "Boone Pickens Stadium",
        abbrev: "OKST",
        colors: {
            primary: "#FF7300",
            secondary: "#000000",
        },
        logo: "/logos/Oklahoma_State_Cowboys_logo_300x300.png",
    },
    {
        id: "odu",
        name: "Old Dominion",
        nickName: "Monarchs",
        city: "Norfolk",
        state: "Virginia",
        conference: "Sun Belt",
        stadium: "S.B. Ballard Stadium",
        abbrev: "ODU",
        colors: {
            primary: "#05344C",
            secondary: "#7c878e",
            accent: "#92c1e9",
        },
        logo: "/logos/Old_Dominion_Monarchs_logo_300x300.png",
    },
    {
        id: "miss",
        name: "Ole Miss",
        nickName: "Rebels",
        city: "Oxford",
        state: "Mississippi",
        conference: "SEC",
        stadium: "Vaught-Hemingway Stadium",
        abbrev: "MISS",
        colors: {
            primary: "#00205b",
            secondary: "#c8102e",
        },
        logo: "/logos/Ole_Miss_Rebels_logo_300x300.png",
    },
    {
        id: "ore",
        name: "Oregon",
        nickName: "Ducks",
        city: "Eugene",
        state: "Oregon",
        conference: "Big Ten",
        stadium: "Autzen Stadium",
        abbrev: "ORE",
        colors: {
            primary: "#154733",
            secondary: "#FEE123",
        },
        logo: "/logos/Oregon_Ducks_logo_300x300.png",
    },
    {
        id: "orst",
        name: "Oregon State",
        nickName: "Beavers",
        city: "Corvallis",
        state: "Oregon",
        conference: "Pac-12",
        stadium: "Reser Stadium",
        abbrev: "ORST",
        colors: {
            primary: "#C34500",
            secondary: "#000000",
        },
        logo: "/logos/Oregon_State_Beavers_logo_300x300.png",
    },
    {
        id: "psu",
        name: "Penn State",
        nickName: "Nittany Lions",
        city: "University Park",
        state: "Pennsylvania",
        conference: "Big Ten",
        stadium: "Beaver Stadium",
        abbrev: "PSU",
        colors: {
            primary: "#041e42",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Penn_State_Nittany_Lions_logo_300x300.png",
    },
    {
        id: "pitt",
        name: "Pittsburgh",
        nickName: "Panthers",
        city: "Pittsburgh",
        state: "Pennsylvania",
        conference: "ACC",
        stadium: "Acrisure Stadium",
        abbrev: "PITT",
        colors: {
            primary: "#1c2957",
            secondary: "#cdb87d",
        },
        logo: "/logos/Pittsburgh_Panthers_logo_300x300.png",
    },
    {
        id: "pur",
        name: "Purdue",
        nickName: "Boilermakers",
        city: "West Lafayette",
        state: "Indiana",
        conference: "Big Ten",
        stadium: "Ross-Ade Stadium",
        abbrev: "PUR",
        colors: {
            primary: "#000000",
            secondary: "#CEB888",
        },
        logo: "/logos/Purdue_Boilermakers_logo_300x300.png",
    },
    {
        id: "rice",
        name: "Rice",
        nickName: "Owls",
        city: "Houston",
        state: "Texas",
        conference: "AAC",
        stadium: "Rice Stadium",
        abbrev: "RICE",
        colors: {
            primary: "#002469",
            secondary: "#5e6062",
        },
        logo: "/logos/Rice_Owls_logo_300x300.png",
    },
    {
        id: "rutg",
        name: "Rutgers",
        nickName: "Scarlet Knights",
        city: "Piscataway",
        state: "New Jersey",
        conference: "Big Ten",
        stadium: "SHI Stadium",
        abbrev: "RUTG",
        colors: {
            primary: "#d21034",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Rutgers_Scarlet_Knights_logo_300x300.png",
    },
    {
        id: "sac",
        name: "Sacramento State",
        nickName: "Hornets",
        city: "Sacramento",
        state: "California",
        conference: "MAC",
        stadium: "Hornet Stadium",
        abbrev: "SAC",
        colors: {
            primary: "#043927",
            secondary: "#C4B581",
        },
        logo: "/logos/Sacramento_State_Hornets_logo_300x300.png",
    },
    {
        id: "sam",
        name: "Sam Houston",
        nickName: "Bearkats",
        city: "Hunstville",
        state: "Texas",
        conference: "C-USA",
        stadium: "Bowers Stadium",
        abbrev: "SAM",
        colors: {
            primary: "#f37021",
            secondary: "#00539f",
        },
        logo: "/logos/Sam_Houston_Bearkats_logo_300x300.png",
    },
    {
        id: "sdsu",
        name: "San Diego State",
        nickName: "Aztecs",
        city: "San Diego",
        state: "California",
        conference: "Pac-12",
        stadium: "Snapdragon Stadium",
        abbrev: "SDSU",
        colors: {
            primary: "#C41230",
            secondary: "#000000",
        },
        logo: "/logos/San_Diego_State_Aztecs_logo_300x300.png",
    },
    {
        id: "sjsu",
        name: "San Jose State",
        nickName: "Spartans",
        city: "San Jose",
        state: "California",
        conference: "MWC",
        stadium: "CEFCU Stadium",
        abbrev: "SJSU",
        colors: {
            primary: "#0055A2",
            secondary: "#FFFFFF",
            accent: "#E5A823",
        },
        logo: "/logos/San_Jose_State_Spartans_logo_300x300.png",
    },
    {
        id: "smu",
        name: "SMU",
        nickName: "Mustangs",
        city: "University Park",
        state: "Texas",
        conference: "ACC",
        stadium: "Gerald J. Ford Stadium",
        abbrev: "SMU",
        colors: {
            primary: "#354ca1",
            secondary: "#cd2027",
        },
        logo: "/logos/SMU_Mustangs_logo_300x300.png",
    },
    {
        id: "usa",
        name: "South Alabama",
        nickName: "Jaguars",
        city: "Mobile",
        state: "Alabama",
        conference: "Sun Belt",
        stadium: "Hancock Whitney Stadium",
        abbrev: "USA",
        colors: {
        primary: "#00205B",
            secondary: "#FFFFFF",
            accent: "#BF0D3E",
        },
        logo: "/logos/South_Alabama_Jaguars_logo_300x300.png",
    },
    {
        id: "scar",
        name: "South Carolina",
        nickName: "Gamecocks",
        city: "Columbia",
        state: "South Carolina",
        conference: "SEC",
        stadium: "Williams-Brice Stadium",
        abbrev: "SCAR",
        colors: {
            primary: "#73000A",
            secondary: "#000000",
        },
        logo: "/logos/South_Carolina_Gamecocks_logo_300x300.png",
    },
    {
        id: "usf",
        name: "South Florida",
        nickName: "Bulls",
        city: "Tampa",
        state: "Florida",
        conference: "AAC",
        stadium: "Raymond James Stadium",
        abbrev: "USF",
        colors: {
            primary: "#006747",
            secondary: "#CFC493",
        },
        logo: "/logos/South_Florida_Bulls_logo_300x300.png",
    },
    {
        id: "usm",
        name: "Southern Miss",
        nickName: "Golden Eagles",
        city: "Hattiesburg",
        state: "Mississippi",
        conference: "Sun Belt",
        stadium: "M.M. Roberts Stadium",
        abbrev: "USM",
        colors: {
            primary: "#000000",
            secondary: "#FDC737",
        },
        logo: "/logos/Southern_Miss_Golden_Eagles_logo_300x300.png",
    },
    {
        id: "stan",
        name: "Stanford",
        nickName: "Cardinal",
        city: "Stanford",
        state: "California",
        conference: "ACC",
        stadium: "Stanford Stadium",
        abbrev: "STAN",
        colors: {
            primary: "#8C1515",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Stanford_Cardinal_logo_300x300.png",
    },
    {
        id: "syr",
        name: "Syracuse",
        nickName: "Orange",
        city: "Syracuse",
        state: "New York",
        conference: "ACC",
        stadium: "JMA Wireless Dome",
        abbrev: "SYR",
        colors: {
            primary: "#D44500",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Syracuse_Orange_logo_300x300.png",
    },
    {
        id: "tcu",
        name: "TCU",
        nickName: "Horned Frogs",
        city: "Fort Worth",
        state: "Texas",
        conference: "Big 12",
        stadium: "Amon G. Carter Stadium",
        abbrev: "TCU",
        colors: {
            primary: "#4d1979",
            secondary: "#FFFFFF",
        },
        logo: "/logos/TCU_Horned_Frogs_logo_300x300.png",
    },
    {
        id: "tem",
        name: "Temple",
        nickName: "Owls",
        city: "Philadelphia",
        state: "Pennsylvania",
        conference: "AAC",
        stadium: "Lincoln Financial Field",
        abbrev: "TEM",
        colors: {
            primary: "#990033",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Temple_Owls_logo_300x300.png",
    },
    {
        id: "tenn",
        name: "Tennessee",
        nickName: "Volunteers",
        city: "Knoxville",
        state: "Tennessee",
        conference: "SEC",
        stadium: "Neyland Stadium",
        abbrev: "TENN",
        colors: {
            primary: "#FF8200",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Tennessee_Volunteers_logo_300x300.png",
    },
    {
        id: "tex",
        name: "Texas",
        nickName: "Longhorns",
        city: "Austin",
        state: "Texas",
        conference: "SEC",
        stadium: "Darrell K Royal-Texas Memorial Stadium",
        abbrev: "TEX",
        colors: {
            primary: "#BF5700",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Texas_Longhorns_logo_300x300.png",
    },
    {
        id: "tamu",
        name: "Texas A&M",
        nickName: "Aggies",
        city: "College Station",
        state: "Texas",
        conference: "SEC",
        stadium: "Kyle Field",
        abbrev: "TAMU",
        colors: {
            primary: "#500000",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Texas_A&M_Aggies_logo_300x300.png",
    },
    {
        id: "txst",
        name: "Texas State",
        nickName: "Bobcats",
        city: "San Marcos",
        state: "Texas",
        conference: "Pac-12",
        stadium: "Bobcat Stadium",
        abbrev: "TXST",
        colors: {
            primary: "#501214",
            secondary: "#8D734A",
        },
        logo: "/logos/Texas_State_Bobcats_logo_300x300.png",
    },
    {
        id: "ttu",
        name: "Texas Tech",
        nickName: "Red Raiders",
        city: "Lubbock",
        state: "Texas",
        conference: "Big 12",
        stadium: "Jones AT&T Stadium",
        abbrev: "TTU",
        colors: {
            primary: "#CC0000",
            secondary: "#000000",
        },
        logo: "/logos/Texas_Tech_Red_Raiders_logo_300x300.png",
    },
    {
        id: "tol",
        name: "Toledo",
        nickName: "Rockets",
        city: "Toledo",
        state: "Ohio",
        conference: "MAC",
        stadium: "Glass Bowl",
        abbrev: "TOL",
        colors: {
            primary: "#002569",
            secondary: "#ffce00",
        },
        logo: "/logos/Toledo_Rockets_logo_300x300.png",
    },
    {
        id: "troy",
        name: "Troy",
        nickName: "Trojans",
        city: "Troy",
        state: "Alabama",
        conference: "Sun Belt",
        stadium: "Veterans Memorial Stadium",
        abbrev: "TROY",
        colors: {
            primary: "#862633",
            secondary: "#8a8d8f",
            accent: "#000000",
        },
        logo: "/logos/Troy_Trojans_logo_300x300.png",
    },
    {
        id: "tuln",
        name: "Tulane",
        nickName: "Green Wave",
        city: "New Orleans",
        state: "Louisiana",
        conference: "AAC",
        stadium: "Yulman Stadium",
        abbrev: "TULN",
        colors: {
        primary: "#006747",
            secondary: "#43B02A",
            accent: "#418FDE",
            extra: "#FFFFFF",
        },
        logo: "/logos/Tulane_Green_Wave_logo_300x300.png",
    },
    {
        id: "tlsa",
        name: "Tulsa",
        nickName: "Golden Hurricane",
        city: "Tulsa",
        state: "Oklahoma",
        conference: "AAC",
        stadium: "Skelly Field at H. A. Chapman Stadium",
        abbrev: "TLSA",
        colors: {
            primary: "#c5b783",
            secondary: "#002d72",
            accent: "#c8102e",
        },
        logo: "/logos/Tulsa_Golden_Hurricane_logo_300x300.png",
    },
    {
        id: "uab",
        name: "UAB",
        nickName: "Blazers",
        city: "Birmingham",
        state: "Alabama",
        conference: "AAC",
        stadium: "Protective Stadium",
        abbrev: "UAB",
        colors: {
            primary: "#000000",
            secondary: "#FFFFFF",
        },
        logo: "/logos/UAB_Blazers_logo_300x300.png",
    },
    {
        id: "ucf",
        name: "UCF",
        nickName: "Knights",
        city: "Orlando",
        state: "Florida",
        conference: "Big 12",
        stadium: "FBC Mortgage Stadium",
        abbrev: "UCF",
        colors: {
            primary: "#000000",
            secondary: "#BA9B37",
        },
        logo: "/logos/UCF_Knights_logo_300x300.png",
    },
    {
        id: "ucla",
        name: "UCLA",
        nickName: "Bruins",
        city: "Pasadena",
        state: "California",
        conference: "Big Ten",
        stadium: "Rose Bowl",
        abbrev: "UCLA",
        colors: {
            primary: "#0072ce",
            secondary: "#ffc72c",
        },
        logo: "/logos/UCLA_Bruins_300x300.png",
    },
    {
        id: "conn",
        name: "UConn",
        nickName: "Huskies",
        city: "East Hartford",
        state: "Connecticut",
        conference: "Independents",
        stadium: "Pratt & Whitney Stadium at Rentschler Field",
        abbrev: "CONN",
        colors: {
            primary: "#000E2F",
            secondary: "#FFFFFF",
        },
        logo: "/logos/UConn_Huskies_logo_300x300.png",
    },
    {
        id: "umass",
        name: "UMass",
        nickName: "Minuteman",
        city: "Hadley",
        state: "Massachusetts",
        conference: "MAC",
        stadium: "Warren McGuirk Alumni Stadium",
        abbrev: "UMASS",
        colors: {
            primary: "#881c1c",
            secondary: "#FFFFFF",
        },
        logo: "/logos/UMass_Minuteman_logo_300x300.png",
    },
    {
        id: "unlv",
        name: "UNLV",
        nickName: "Rebels",
        city: "Las Vegas",
        state: "Nevada",
        conference: "MWC",
        stadium: "Allegiant Stadium",
        abbrev: "UNLV",
        colors: {
            primary: "#B10202",
            secondary: "#666666",
        },
        logo: "/logos/UNLV_Rebels_logo_300x300.png",
    },
    {
        id: "usc",
        name: "USC",
        nickName: "Trojans",
        city: "Los Angeles",
        state: "California",
        conference: "Big Ten",
        stadium: "Los Angeles Memorial Coliseum",
        abbrev: "USC",
        colors: {
            primary: "#990000",
            secondary: "#FFCC00",
            accent: "#FFFFFF",
        },
        logo: "/logos/USC_Trojans_logo_300x300.png",
    },
    {
        id: "utep",
        name: "UTEP",
        nickName: "Miners",
        city: "El Paso",
        state: "Texas",
        conference: "MWC",
        stadium: "Sun Bowl",
        abbrev: "UTEP",
        colors: {
            primary: "#002147",
            secondary: "#FF5600",
            accent: "#B2B4B3",
        },
        logo: "/logos/UTEP_Miners_logo_300x300.png",
    },
    {
        id: "utsa",
        name: "UTSA",
        nickName: "Roadrunners",
        city: "San Antonio",
        state: "Texas",
        conference: "AAC",
        stadium: "Alamodome",
        abbrev: "UTSA",
        colors: {
            primary: "#0c2340",
            secondary: "#FFFFFF",
            accent: "#f15a22",
        },
        logo: "/logos/UTSA_Roadrunners_logo_300x300.png",
    },
    {
        id: "utah",
        name: "Utah",
        nickName: "Utes",
        city: "Salt Lake City",
        state: "Utah",
        conference: "Big 12",
        stadium: "Rice-Eccles Stadium",
        abbrev: "UTAH",
        colors: {
            primary: "#CC0000",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Utah_Utes_logo_300x300.png",
    },
    {
        id: "usu",
        name: "Utah State",
        nickName: "Aggies",
        city: "Logan",
        state: "Utah",
        conference: "Pac-12",
        stadium: "Maverik Stadium",
        abbrev: "USU",
        colors: {
        primary: "#0F2439",
            secondary: "#FFFFFF",
            accent: "#9D968D",
        },
        logo: "/logos/Utah_State_Aggies_logo_300x300.png",
    },
    {
        id: "van",
        name: "Vanderbilt",
        nickName: "Commodores",
        city: "Nashville",
        state: "Tennessee",
        conference: "SEC",
        stadium: "FirstBank Stadium",
        abbrev: "VAN",
        colors: {
            primary: "#000000",
            secondary: "#997F3D",
        },
        logo: "/logos/Vanderbilt_Commodores_logo_300x300.png",
    },
    {
        id: "uva",
        name: "Virginia",
        nickName: "Cavaliers",
        city: "Charlottesville",
        state: "Virginia",
        conference: "ACC",
        stadium: "Scott Stadium",
        abbrev: "UVA",
        colors: {
            primary: "#041e42",
            secondary: "#fa4616",
        },
        logo: "/logos/Virginia_Cavaliers_logo_300x300.png",
    },
    {
        id: "vt",
        name: "Virginia Tech",
        nickName: "Hokies",
        city: "Blacksburg",
        state: "Virginia",
        conference: "ACC",
        stadium: "Lane Stadium",
        abbrev: "VT",
        colors: {
            primary: "#660000",
            secondary: "#FF6600",
        },
        logo: "/logos/Virginia_Tech_Hokies_logo_300x300.png",
    },
    {
        id: "wake",
        name: "Wake Forest",
        nickName: "Demon Deacons",
        city: "Winston-Salem",
        state: "North Carolina",
        conference: "ACC",
        stadium: "Allegacy Federal Credit Union Stadium",
        abbrev: "WAKE",
        colors: {
            primary: "#000000",
            secondary: "#9E7E38",
        },
        logo: "/logos/Wake_Forest_Demon_Deacons_logo_300x300.png",
    },
    {
        id: "uw",
        name: "Washington",
        nickName: "Huskies",
        city: "Seattle",
        state: "Washington",
        conference: "Big Ten",
        stadium: "Husky Stadium",
        abbrev: "UW",
        colors: {
            primary: "#363c74",
            secondary: "#e8d3a2",
        },
        logo: "/logos/Washington_Huskies_logo_300x300.png",
    },
    {
        id: "wsu",
        name: "Washington State",
        nickName: "Cougars",
        city: "Pullman",
        state: "Washington",
        conference: "Pac-12",
        stadium: "Martin Stadium",
        abbrev: "WSU",
        colors: {
            primary: "#981e32",
            secondary: "#5e6a71",
        },
        logo: "/logos/Washington_State_Cougars_logo_300x300.png",
    },
    {
        id: "wvu",
        name: "West Virginia",
        nickName: "Mountaineers",
        city: "Morgantown",
        state: "West Virginia",
        conference: "Big 12",
        stadium: "Milan Puskar Stadium",
        abbrev: "WVU",
        colors: {
            primary: "#002855",
            secondary: "#EAAA00",
        },
        logo: "/logos/West_Virginia_Mountaineers_logo_300x300.png",
    },
    {
        id: "wku",
        name: "Western Kentucky",
        nickName: "Hilltoppers",
        city: "Bowling Green",
        state: "Kentucky",
        conference: "C-USA",
        stadium: "Houchens Industries-L. T. Smith Stadium",
        abbrev: "WKU",
        colors: {
            primary: "#B01E24",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Western_Kentucky_Hilltoppers_logo_300x300.png",
    },
    {
        id: "wmu",
        name: "Western Michigan",
        nickName: "Broncos",
        city: "Kalamazoo",
        state: "Michigan",
        conference: "MAC",
        stadium: "Waldo Stadium",
        abbrev: "WMU",
        colors: {
            primary: "#6c4023",
            secondary: "#b5a167",
        },
        logo: "/logos/Western_Michigan_Broncos_logo_300x300.png",
    },
    {
        id: "wis",
        name: "Wisconsin",
        nickName: "Badgers",
        city: "Madison",
        state: "Wisconsin",
        conference: "Big Ten",
        stadium: "Camp Randall Stadium",
        abbrev: "WIS",
        colors: {
            primary: "#c5050c",
            secondary: "#FFFFFF",
        },
        logo: "/logos/Wisconsin_Badgers_logo_300x300.png",
    },
    {
        id: "wyo",
        name: "Wyoming",
        nickName: "Cowboys",
        city: "Laramie",
        state: "Wyoming",
        conference: "MWC",
        stadium: "War Memorial Stadium",
        abbrev: "WYO",
        colors: {
            primary: "#492f24",
            secondary: "#ffc425",
        },
        logo: "/logos/Wyoming_Cowboys_logo_300x300.png",
    },
];
