// lib/pipelines.ts

export const pipelines = [
    'East Texas',
    'North Texas',
    'Southern California',
    'Metro Atlanta',
    'Central Florida',
    'South Florida',
    'Tidewater',
    'Big Apple',
    'Ohio',
    'Alabama',
    'North Carolina',
    'Michigan',
    'Northern California',
    'Louisiana',
    'South Georgia',
    'Tennessee',
    'Illinois',
    'South Carolina',
    'Mississippi',
    'Pacific Northwest',
    'North Florida',
    'Pennsylvania',
    'Indiana',
    'Arizona',
    'Missouri',
    'Utah',
    'Oklahoma',
    'New England',
    'Nevada',
    'Wisconsin',
    'Colorado',
    'Kentucky',
    'Southwest Texas',
    'Hawaii',
    'Arkansas',
    'Kansas',
    'Iowa',
    'Minnesota',
    'Nebraska',
    'West Virginia',
    'New Mexico',
    'Big Sky',
]
